### ISSUE TITLE
Missing closing parenthesis in nwmatcher-cache.js

### ISSUE THREAD

**Issue by monsieurwei** [dperini/nwmatcher#111] opened 2017-10-17 21:21 UTC
commit c5ce6113e71d704bfda35a382d4b377efe4e1238 accidentally deleted a closing parenthesis on line 25 of nwmatcher-cache.js

**Comment by dperini** [comment] 2017-11-11 18:16
@monsieurwei 
sorry for the delay but I have been busy working on completing the "nwsapi" project which is the followup improvement of "nwmatcher". Also that file you mention is not currently used anywhere that I am aware of,  however I can confirm the problem you spotted is correct, a closing parenthesis is missing, lost by mistake between commits (as you noticed in commit c5ce611).
I will correct it asap  but I believe it would be better to completely remove that obsoleted file.
I also suggest you use "nwsapi" instead of "nwmatcher" since it is much faster, have more features and is a step forward regarding Selectors Level 3/4 support.

**Comment by dperini** [comment] 2017-11-30 10:45
Fixed by 4d6967c

**Closed by dperini** 2017-11-30 10:45 UTC

**Comment by SidneyNemzer** [comment] 2018-03-30 18:34
> I have been busy working on completing the "nwsapi" project which is the followup improvement of "nwmatcher"... I also suggest you use "nwsapi" instead of "nwmatcher" since it is much faster, have more features and is a step forward regarding Selectors Level 3/4 support.

Glad to hear things are progressing! Do you think there should be a note in the README of this repo directing people to the new project?
